In [1]:
import pandas as pd
import numpy as np

In [165]:
dt =  pd.read_csv('datasets/subset.csv')

In [ ]:
dt

In [12]:
#Procurar nulos
dt.isnull().sum()

app_id                           0
app_name                         0
timestamp_created                0
recommended                      0
language                         0
review                       11612
votes_helpful                    0
comment_count                    0
author.steamid                   0
author.num_games_owned           0
author.num_reviews               0
author.playtime_at_review        0
dtype: int64

In [16]:
#Ver duplicatas
duplicates_per_column = dt.apply(lambda x: x.duplicated().sum())
print(duplicates_per_column)

app_id                       5901106
app_name                     5901106
timestamp_created             257618
recommended                  5901419
language                     5901420
review                       1254720
votes_helpful                5899770
comment_count                5901205
author.steamid               2293985
author.num_games_owned       5895988
author.num_reviews           5900713
author.playtime_at_review    5897220
dtype: int64

In [143]:
#Remover as colunas inúteis da base subset(Original)
BaseOLimpa = dt.drop(["timestamp_created", "language", "review", "comment_count", "author.num_reviews", "author.num_games_owned"], axis= 1)
BaseOLimpa.info

<bound method DataFrame.info of          app_id                  app_name  recommended  votes_helpful  \
0        292030  The Witcher 3: Wild Hunt         True              0
1        292030  The Witcher 3: Wild Hunt         True              0
2        292030  The Witcher 3: Wild Hunt         True              0
3        292030  The Witcher 3: Wild Hunt         True              0
4        292030  The Witcher 3: Wild Hunt         True              0
...         ...                       ...          ...            ...
5901416  546560           Half-Life: Alyx         True              1
5901417  546560           Half-Life: Alyx         True              1
5901418  546560           Half-Life: Alyx         True              2
5901419  546560           Half-Life: Alyx         True              0
5901420  546560           Half-Life: Alyx         True              0

            author.steamid  author.playtime_at_review
0        76561198170193529                      823.0
1        76561198119302812                     4192.0
2        76561198284845223                     2518.0
3        76561198370568524                      517.0
4        76561198040150323                      165.0
...                    ...                        ...
5901416  76561198824257821                     2230.0
5901417  76561198003907172                     1083.0
5901418  76561198020563704                     1513.0
5901419  76561198032433284                      752.0
5901420  76561198070261770                      232.0

[5901421 rows x 6 columns]>

In [144]:
BaseOLimpa

,app_id,app_name,recommended,votes_helpful,author.steamid,author.playtime_at_review
0,292030,The Witcher 3: Wild Hunt,True,0,76561198170193529,823.0
1,292030,The Witcher 3: Wild Hunt,True,0,76561198119302812,4192.0
2,292030,The Witcher 3: Wild Hunt,True,0,76561198284845223,2518.0
3,292030,The Witcher 3: Wild Hunt,True,0,76561198370568524,517.0
4,292030,The Witcher 3: Wild Hunt,True,0,76561198040150323,165.0
...,...,...,...,...,...,...
5901416,546560,Half-Life: Alyx,True,1,76561198824257821,2230.0
5901417,546560,Half-Life: Alyx,True,1,76561198003907172,1083.0
5901418,546560,Half-Life: Alyx,True,2,76561198020563704,1513.0
5901419,546560,Half-Life: Alyx,True,0,76561198032433284,752.0
5901420,546560,Half-Life: Alyx,True,0,76561198070261770,232.0

In [166]:
#Base Games
BaseGames = pd.read_csv("datasets/games.csv")

In [ ]:
BaseGames

In [104]:
#Base Games após limpeza de colunas
Games = BaseGames[['AppID', 'Categories', "Genres", "Tags"]]

In [ ]:
Games

In [106]:
#Nulos da base Games
Games.isnull().sum()

AppID             6
Categories     5913
Genres         4841
Tags          29763
dtype: int64

In [145]:
#Remoção de nulos da coluna AppID
Games = Games.dropna(subset=["AppID"])
Games.isnull().sum()

AppID             0
Categories     5910
Genres         4839
Tags          29757
dtype: int64

In [152]:
#Remoção das linhas onde as 3 colunas estão com nulo(ao mesmo tempo)
GamesLimpeza = Games.dropna(subset = ["Categories", "Genres", "Tags"], how = 'all')

In [153]:
GamesLimpeza.isnull().sum()

AppID             0
Categories     1242
Genres          171
Tags          25089
dtype: int64

In [154]:
#Concatenar as 2 bases
gamesteste = GamesLimpeza.rename(columns={'AppID': 'app_name'})

In [155]:
# Fazer o merge das bases
BaseFinal = pd.merge(BaseOLimpa, gamesteste[['app_name', 'Categories', 'Genres', 'Tags']], on='app_name', how='left')

In [156]:
BaseFinal

,app_id,app_name,recommended,votes_helpful,author.steamid,author.playtime_at_review,Categories,Genres,Tags
0,292030,The Witcher 3: Wild Hunt,True,0,76561198170193529,823.0,NaN,NaN,NaN
1,292030,The Witcher 3: Wild Hunt,True,0,76561198119302812,4192.0,NaN,NaN,NaN
2,292030,The Witcher 3: Wild Hunt,True,0,76561198284845223,2518.0,NaN,NaN,NaN
3,292030,The Witcher 3: Wild Hunt,True,0,76561198370568524,517.0,NaN,NaN,NaN
4,292030,The Witcher 3: Wild Hunt,True,0,76561198040150323,165.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6010648,546560,Half-Life: Alyx,True,1,76561198824257821,2230.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure","VR,FPS,Story Rich,Horror,Female Protagonist,Sh..."
6010649,546560,Half-Life: Alyx,True,1,76561198003907172,1083.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure","VR,FPS,Story Rich,Horror,Female Protagonist,Sh..."
6010650,546560,Half-Life: Alyx,True,2,76561198020563704,1513.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure","VR,FPS,Story Rich,Horror,Female Protagonist,Sh..."
6010651,546560,Half-Life: Alyx,True,0,76561198032433284,752.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure","VR,FPS,Story Rich,Horror,Female Protagonist,Sh..."
6010652,546560,Half-Life: Alyx,True,0,76561198070261770,232.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure","VR,FPS,Story Rich,Horror,Female Protagonist,Sh..."

In [158]:
teste = BaseFinal.dropna(subset = ["Categories", "Genres", "Tags"], how = 'all')

In [161]:
Base = teste.drop(["Tags"], axis=1)

In [162]:
Base

,app_id,app_name,recommended,votes_helpful,author.steamid,author.playtime_at_review,Categories,Genres
72593,70,Half-Life,False,0,76561198352346016,530.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action
72594,70,Half-Life,True,0,76561198074088375,237.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action
72595,70,Half-Life,True,0,76561198945746887,3297.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action
72596,70,Half-Life,True,0,76561198911822629,1015.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action
72597,70,Half-Life,True,0,76561198956790263,1145.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action
...,...,...,...,...,...,...,...,...
6010648,546560,Half-Life: Alyx,True,1,76561198824257821,2230.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure"
6010649,546560,Half-Life: Alyx,True,1,76561198003907172,1083.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure"
6010650,546560,Half-Life: Alyx,True,2,76561198020563704,1513.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure"
6010651,546560,Half-Life: Alyx,True,0,76561198032433284,752.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure"
6010652,546560,Half-Life: Alyx,True,0,76561198070261770,232.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure"

In [163]:
Base.to_csv('datasets/Base.csv', index=False)

In [9]:
Base = pd.read_csv('datasets/Base.csv')

In [39]:
Base

,app_id,app_name,recommended,votes_helpful,author.steamid,author.playtime_at_review,Categories,Genres,interaction
0,70,Half-Life,False,0,76561198352346016,530.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action,-1
1,70,Half-Life,True,0,76561198074088375,237.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action,1
2,70,Half-Life,True,0,76561198945746887,3297.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action,1
3,70,Half-Life,True,0,76561198911822629,1015.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action,1
4,70,Half-Life,True,0,76561198956790263,1145.0,"Single-player,Multi-player,PvP,Online PvP,Stea...",Action,1
...,...,...,...,...,...,...,...,...,...
4963320,546560,Half-Life: Alyx,True,1,76561198824257821,2230.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure",2
4963321,546560,Half-Life: Alyx,True,1,76561198003907172,1083.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure",2
4963322,546560,Half-Life: Alyx,True,2,76561198020563704,1513.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure",3
4963323,546560,Half-Life: Alyx,True,0,76561198032433284,752.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure",1
4963324,546560,Half-Life: Alyx,True,0,76561198070261770,232.0,"Single-player,Steam Achievements,Captions avai...","Action,Adventure",1

In [ ]:
# Criando a coluna de interação com as regras descritas
Base['interaction'] = np.where(
    (Base['recommended'] == True) & (Base['votes_helpful'] == 0), 1,
    np.where(
        (Base['recommended'] == False) & (Base['votes_helpful'] == 0), -1,
        np.where(
            Base['recommended'] == True, 1 + Base['votes_helpful'],
            -1 - Base['votes_helpful']
        )
    )
)

In [40]:
# Convertendo 'Categories' e 'Genres' em listas, caso estejam em formato string
Base['Categories'] = Base['Categories'].fillna('').str.split(', ')
Base['Genres'] = Base['Genres'].fillna('').str.split(', ')

# Aplicando One-Hot Encoding para 'Categories'
categories_dummies = Base['Categories'].str.join('|').str.get_dummies()

# Aplicando One-Hot Encoding para 'Genres'
genres_dummies = Base['Genres'].str.join('|').str.get_dummies()

# Concatenando os dummies ao dataframe original
df = pd.concat([Base, categories_dummies, genres_dummies], axis=1)

In [42]:
# Definindo novos jogos (sem interações anteriores)
all_games = set(df['app_id'].unique())
interacted_games = set(df[df['recommended'].notna()]['app_id'].unique())
new_games_ids = list(all_games - interacted_games)

# Selecionando as categorias e gêneros que o usuário gosta, com base nas interações positivas
user_id = 76561198062813911  # Exemplo de ID de usuário
user_liked_games = df[(df['author.steamid'] == user_id) & (df['recommended'] == True)]
user_preferred_categories = user_liked_games[categories_dummies.columns].sum()
user_preferred_genres = user_liked_games[genres_dummies.columns].sum()

# Encontrar novos jogos com categorias e gêneros semelhantes
recommended_new_games = df[(df['app_id'].isin(new_games_ids)) & 
                           (df[categories_dummies.columns].dot(user_preferred_categories) > 0) &
                           (df[genres_dummies.columns].dot(user_preferred_genres) > 0)]['app_name'].unique()

print("Novos jogos recomendados para o usuário:", recommended_new_games)

MemoryError: Unable to allocate 11.2 GiB for an array with shape (302, 4963325) and data type int64

In [18]:
# Gerando a matriz usuário-jogo com os novos valores de interação
user_item_matrix = Base.pivot_table(index='author.steamid', columns='app_id', values='interaction', fill_value=0)

In [22]:
from implicit.als import AlternatingLeastSquares
import scipy.sparse as sparse

# Convertendo a matriz para formato esparso
sparse_user_item = sparse.csr_matrix(user_item_matrix.values)

# Configurando e treinando o modelo ALS
model = AlternatingLeastSquares(factors=20, regularization=0.1, iterations=20)
model.fit(sparse_user_item)

C:\Users\celso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\celso\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\implicit\cpu\als.py:95: RuntimeWarning: OpenBLAS is configured to use 12 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
100%|██████████| 20/20 [01:40<00:00,  5.04s/it]

In [26]:
# Definindo o ID do usuário
user_id = 76561198062813911

# Obtendo o índice do usuário na matriz
# Extraindo as interações específicas para o usuário
user_interactions = sparse_user_item[user_index]

In [31]:
# Gerando recomendações para o usuário
recommendations = model.recommend(user_index, user_interactions)

# Inspecionando o conteúdo de recommendations
print("Conteúdo de recommendations:", recommendations)

Conteúdo de recommendations: (array([112,  22,  75,  62,  45,  47,  12, 187, 198, 259], dtype=int32), array([1.3732615 , 1.0959285 , 1.0752963 , 1.0423183 , 1.0306513 ,
       0.89328367, 0.8928273 , 0.84803957, 0.81430143, 0.77185607],
      dtype=float32))

In [32]:
# Extraindo os índices dos jogos recomendados
recommended_indices = recommendations[0]

# Convertendo os índices de volta para IDs de jogo
recommended_games = [user_item_matrix.columns[i] for i in recommended_indices]
print("Recomendações (app_id) para o usuário:", recommended_games)

Recomendações (app_id) para o usuário: [np.int64(431960), np.int64(212680), np.int64(339800), np.int64(286160), np.int64(255710), np.int64(262060), np.int64(72850), np.int64(629760), np.int64(646570), np.int64(1145360)]

In [33]:
# Obtendo os nomes dos jogos recomendados
recommended_games_names = Base[Base['app_id'].isin(recommended_games)]['app_name'].unique()
print("Jogos recomendados para o usuário:", recommended_games_names)

Jogos recomendados para o usuário: ['Slay the Spire' 'Wallpaper Engine' 'MORDHAU' 'Hades'
 'The Elder Scrolls V: Skyrim' 'FTL: Faster Than Light'
 'Tabletop Simulator' 'HuniePop' 'Cities: Skylines' 'Darkest Dungeon®']

In [34]:
# Somando a coluna de interação para cada jogo para medir a popularidade
popular_games = Base.groupby('app_id')['interaction'].sum().sort_values(ascending=False)

# Selecionando os top N jogos mais populares
top_n = 10  # Número de jogos populares para recomendar
popular_games_ids = popular_games.head(top_n).index.tolist()

# Obter os nomes dos jogos populares
popular_games_names = Base[Base['app_id'].isin(popular_games_ids)]['app_name'].unique()
print("Jogos recomendados para novos usuários:", popular_games_names)

Jogos recomendados para novos usuários: ['Portal 2' "Garry's Mod" 'The Forest' 'Stardew Valley' 'Among Us'
 'Phasmophobia' 'Undertale' 'Bloons TD 6' 'DOOM' 'Terraria']